# Generated by Django 2.0 on 2018-10-24 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRO', '0002_auto_20181017_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeCode', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=200)),
                ('PhoneNo', models.CharField(default=None, max_length=10)),
                ('EmailID', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='Fax',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Organization',
        ),
        migrations.AddField(
            model_name='company',
            name='company_code',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='HRO.Company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
