# Generated by Django 2.0 on 2018-11-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRO', '0003_auto_20181024_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPO_Employee',
            fields=[
                ('EmployeeCode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('EmpType', models.CharField(choices=[('INST', 'Installation'), ('SURV', 'Surveillance'), ('MAIN', 'Maintenance')], default='INST', max_length=15)),
                ('Charge', models.IntegerField(default=10000)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='Deposit',
            field=models.IntegerField(default=10000),
        ),
    ]
