# Generated by Django 2.0 on 2018-11-07 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRO', '0004_auto_20181106_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=2018)),
                ('info', models.FileField(upload_to='ecmdocs/')),
                ('company_code', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='HRO.Company')),
            ],
        ),
    ]
