# Generated by Django 2.0 on 2018-11-07 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRO', '0005_accountinginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinginfo',
            name='company_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HRO.Company'),
        ),
    ]
