# Generated by Django 2.0 on 2018-11-07 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRO', '0006_auto_20181107_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpo_employee',
            name='Rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
