# Generated by Django 2.0 on 2018-11-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRO', '0007_bpo_employee_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpo_employee',
            name='Age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='bpo_employee',
            name='EmailID',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='bpo_employee',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='bpo_employee',
            name='PhoneNo',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='bpo_employee',
            name='isAvail',
            field=models.BooleanField(default=True),
        ),
    ]
