# Generated by Django 2.0 on 2018-11-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRO', '0008_auto_20181107_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bpo_employee',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='bpo_employee',
            name='EmailID',
        ),
        migrations.RemoveField(
            model_name='bpo_employee',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='bpo_employee',
            name='PhoneNo',
        ),
        migrations.RemoveField(
            model_name='bpo_employee',
            name='isAvail',
        ),
    ]
