# Generated by Django 2.0 on 2018-11-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRO', '0010_auto_20181107_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpo_employee',
            name='Age',
            field=models.IntegerField(default=30, null=True),
        ),
    ]
