# Generated by Django 2.0 on 2018-11-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRO', '0011_auto_20181107_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bpo_employee',
            name='Age',
        ),
    ]
