# Generated by Django 2.0 on 2018-11-07 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRO', '0012_remove_bpo_employee_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='EmployeeCode',
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HRO.Company'),
        ),
    ]
