# Generated by Django 2.0 on 2018-11-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRO', '0013_auto_20181107_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='HCARequest',
            field=models.IntegerField(default=1),
        ),
    ]
