# Generated by Django 2.0 on 2018-11-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRO', '0014_employee_hcarequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='RequestAmount',
            field=models.IntegerField(default=0),
        ),
    ]
